### ISSUE TITLE
Ruby requires a newline in order for the program to be interpreted and run.

### ISSUE THREAD

**Issue by harrisreynolds** [radian-software/riju#116]
This is without doing anything...

![image](https://user-images.githubusercontent.com/1183747/134578996-82b53f58-74fd-4c27-bf41-a6075cdb4666.png)

If I add a new line at the bottom it works:

![image](https://user-images.githubusercontent.com/1183747/134579121-1cdc9eed-5898-4bc1-b531-5ef6fa9ae323.png)

**Comment by raxod502** [comment]
Thanks for the report, can confirm. Let me take a look at this, should be a straightforward fix.

**Comment by raxod502** [comment]
The fix for this has been deployed.
