### ISSUE TITLE
Local build of admin-shell fails

### ISSUE THREAD

**Issue by code-leen** [radian-software/riju#124]
Trying to run `make image shell I=admin` fails and outputs this to the console:
```
#8 26.37 Reading state information...
#8 26.39 E: Unable to locate package docker-ce-cli
#8 26.39 E: Unable to locate package terraform
------
executor failed running [/bin/sh -c /tmp/install.bash]: exit code: 100
make: *** [image] Error 1
```
I'm on a macOS with the M1 chip 💻  🍎 

Any help would be appreciated!

**Comment by raxod502** [comment]
You want https://github.com/raxod502/riju/issues/103, which has info and workarounds for running on ARM. It looks like we need to (conditionally?) use an older version of Node.js, and also add an option to `docker build`.
