### ISSUE TITLE
[bug] A+ repl does not load

### ISSUE THREAD

**Issue by mtx2d** [radian-software/riju#127]
Hi team,
I would like to report a bug. 
The link for the A+ language(`https://riju.codes/aplus`) fails to load. 

I have tried this on my desktop as well as my mobile device.

**Comment by raxod502** [comment]
That's no good! Must be something wrong with the alias logic, investigating.

**Comment by raxod502** [comment]
Fixed and deployed in the latest commit. Thanks for the report.
