### ISSUE TITLE
Adding requests

### ISSUE THREAD

**Issue by iam-py-test** [radian-software/riju#128]
I just noticed https://github.com/raxod502/python-in-a-box/issues/3#event-5480924831 was closed, so I figured that I would post the same request here.

It seems that the requests module is not installed, and while it can be installed, that does not persist through reload (which makes sense): 
![image](https://user-images.githubusercontent.com/84232764/137799534-6782f2e5-9f6b-495c-92c2-6c4b0c53b9f5.png)

It would be nice to have it installed by default, but that is not very critical

#### Metadata
Language: Python
Browser: Firefox
Version: 93.0
Relevant URL: https://riju.codes/python

#### Steps to reproduce the issue
- Go to https://riju.codes/python
- Type `import requests` into the IDE section
- Run the program
- Notice the error

#### Expected behavior
Requests is imported successfully

#### Actual behavior
Requests failed to import because it is not installed 
 

#### Checklist
- [X] I have read and understand the contributing guidelines
- [X] This is not a security vulnerability
- [X] I have checked for redundant issues
- [X] I have verified this is not caused by an issue with my code or browser

**Comment by raxod502** [comment]
See https://github.com/raxod502/riju/issues/23 :)
The idea would be that not only can you install that specific package, but any package on PyPI.

I think we can probably close this ticket as a special case of the general one for package installation, if that seems reasonable to you.

**Comment by iam-py-test** [comment]
Ok. Understood 
I must have missed that issue when I was searching for relevant issues
