### ISSUE TITLE
Line numbers missing in C# stack traces

### ISSUE THREAD

**Issue by Shpek** [radian-software/riju#138]
It seems C# is compiled without debug support so the line numbers in the stack traces are missing:

![image](https://user-images.githubusercontent.com/2659777/140317647-ecaa94c4-206a-4a53-8697-043ad4ecd018.png)

**Comment by raxod502** [comment]
Latest commit should fix this, will close this issue once it is deployed.

**Comment by raxod502** [comment]
This may take some time to deploy since upstream changes have broken some aspects of the build system.

**Comment by Shpek** [comment]
Seems to be working now, thanks!

**Comment by raxod502** [comment]
Only took me a month ;)
