### ISSUE TITLE
Bug with terminal

### ISSUE THREAD

**Issue by hello-smile6** [radian-software/riju#153]
![image](https://user-images.githubusercontent.com/73048226/150732459-a396ff0c-b13d-45d2-af6f-d124d9972326.png)
I think sending and recieving each character base64-encoded, similar to how I do it with https://github.com/hello-smile6/libv86-terminal-forwarding/ , might fix it.

**Comment by raxod502** [comment]
Sorry, I'm not sure I understand. What's the expected behavior, and what behavior is being demonstrated in the screenshot?

**Comment by hello-smile6** [comment]
> Sorry, I'm not sure I understand. What's the expected behavior, and what behavior is being demonstrated in the screenshot?

The text is strange when I use NodeJS. I'd expect it to work like running it on the same device. If data is being lost in transmission, you could always base64-encode terminal data before sending it.

**Comment by raxod502** [comment]
Can you please explain what you mean by "strange", as in: what's the expected output, and what behavior are you actually seeing? Also, I won't be able to reproduce this without knowing what input you're giving.

**Comment by hello-smile6** [comment]
> Can you please explain what you mean by "strange", as in: what's the expected output, and what behavior are you actually seeing? Also, I won't be able to reproduce this without knowing what input you're giving.

I was running `child_process` with Node, then typing in the first letter of the word `os` once I did `const os=require("os")`

**Comment by raxod502** [comment]
I don't know what "running `child_process`" means. Can you please clarify exactly what you're typing, and in what order? A video would be even better.

In the following screenshot, I executed `require('child_process').exec('ls -lA')`, then `const os=require("os")`, then typed `o`. I don't see anything out of the ordinary:

![image](https://user-images.githubusercontent.com/6559064/152660305-8b375372-81b8-4f06-b8c3-147db85d2259.png)

**Comment by hello-smile6** [comment]
> I don't know what "running `child_process`" means. Can you please clarify exactly what you're typing, and in what order? A video would be even better.
> 
> In the following screenshot, I executed `require('child_process').exec('ls -lA')`, then `const os=require("os")`, then typed `o`. I don't see anything out of the ordinary:
> 
> ![image](https://user-images.githubusercontent.com/6559064/152660305-8b375372-81b8-4f06-b8c3-147db85d2259.png)

I'll open up a clean Chromium instance once I manage to delete enough files, then I'll record a video.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
