### ISSUE TITLE
Add client-side language support

### ISSUE THREAD

**Issue by hello-smile6** [radian-software/riju#155]
If it was possible to run some languages client-side (e.g. x86 assembly using [v86](https://copy.sh/v86)), maybe things wouldn't be as expensive. Would that be possible?

**Comment by raxod502** [comment]
This is true, but unfortunately it's nowhere near a general-purpose solution. Some platforms that provide similar features to Riju take this approach, but it generally limits you to a small subset of the available languages---most languages require interesting system dependencies that are difficult or impossible to replicate on the client-side, especially if you want reasonable performance. So insofar as universal language support is a design goal for Riju, it has to be server-side.

**Comment by hello-smile6** [comment]
> This is true, but unfortunately it's nowhere near a general-purpose solution. Some platforms that provide similar features to Riju take this approach, but it generally limits you to a small subset of the available languages---most languages require interesting system dependencies that are difficult or impossible to replicate on the client-side, especially if you want reasonable performance. So insofar as universal language support is a design goal for Riju, it has to be server-side.

Would it be possible for something like x86 assembly?

**Comment by raxod502** [comment]
Sure, of course for specific languages---but even then, server-side execution isn't typically a heavy resource load for languages that can be executed client-side. The expensive ones are also impractical to execute client-side! (E.g., Sagemath and its darned 10 GB download size.)
