### ISSUE TITLE
Adding multiple classes in Java

### ISSUE THREAD

**Issue by reesericci** [radian-software/riju#179]
It would be nice if I could add multiple classes in my Java code, something I'm unable to do because Riju only supports one "file" (which I like), but Java requires making each class a new file. Maybe there's a workaround in the JVM to allow for multiple class declarations in one file?

Thanks,

--reese

**Comment by raxod502** [comment]
You can do this by defining the additional classes as package-private (i.e., removing the `public` modifier): https://stackoverflow.com/a/48839136
