### ISSUE TITLE
The page riju.codes doesn't work over IPv4

### ISSUE THREAD

**Issue by pepkin88** [radian-software/riju#189]
The domain has only the AAAA record, but no A records.

**Comment by raxod502** [comment]
Correct. You must be on an IPv6 enabled network to access Riju. If your local network is not IPv6-enabled, you may wish to contact your system administrator and ask them to do their part in moving the world's network infrastructure off of legacy protocols that can no longer support demand.

**Comment by pepkin88** [comment]
I use a popular Polish provider and have only IPv4. To access the page I have to use a VPN.

**Comment by raxod502** [comment]
I understand. At present, using a VPN is what I would recommend to anyone whose local network is IPv4-only.

**Comment by pepkin88** [comment]
OK, fair enough. I assume that it is the limitation of the current hosting provider.

Nevertheless, I wanted to let you know, that there are a lot of people with this issue.
I stumbled upon this page after watching a Primeagen reaction video, and you could see that for people in the chat the page is seen as broken, with no information of how to reach it, or is it even possible: https://youtu.be/e-DDYIOqRI0?t=2750

Some people might want to dig deeper to find the issue (like I did here), but most will probably just give up. 

But no biggie. After all, this is a hobby project sponsored by donations.

**Comment by raxod502** [comment]
Yes, I noticed that as well, and I'm going to update the blog post and GitHub README with this information when I have a chance.

**Comment by raxod502** [comment]
Done in https://github.com/radian-software/riju/commit/553d552047e9b3f03c4d08f782b6346c585c27cf and https://github.com/raxod502/intuitive-explanations/commit/d69e1be092fbf50c500c2a791e175f52b4643c60.
