### ISSUE TITLE
Keyboard shortcut for running the code

### ISSUE THREAD

**Issue by raxod502** [radian-software/riju#38]
_comment imported by @Owen-Gillespie_

Would be nice to be able to run the code without using the mouse. `Cmd + enter` or `Ctrl + enter` seem like intuitive shortcuts.

**Comment by matrixik** [comment]
I think this is already working. https://github.com/raxod502/riju/blob/master/frontend/src/app.js#L398

But I would also like to see shortcut for running `Prettify`.

**Comment by matrixik** [comment]
Or even better formatting the code on run.

**Comment by raxod502** [comment]
Let's close this issue since (as you observed) it's already resolved, and track additional features in additional issues to keep things clean.
