### ISSUE TITLE
eC: segmentation fault

### ISSUE THREAD

**Issue by raxod502** [radian-software/riju#41]
Currently, after a program finishes running in eC, you get a segmentation fault. I do not have any idea why this might be. It might be worth looking into how https://github.com/mame/quine-relay avoids this problem.

**Comment by ryusatgat** [comment]
I got the solution. first, make .epj file like this. on this project, it's name is `main`.
```json
{
   "Version" : 0.2,
   "ModuleName" : "main",
   "Options" : {
      "Warnings" : "All",
      "TargetType" : "Executable",
      "TargetFileName" : "main",
      "Libraries" : [
         "ecere"
      ]
   },
   "Configurations" : [
      {
         "Name" : "Release",
         "Options" : {
            "Debug" : false,
            "Optimization" : "Speed",
            "FastMath" : true
         }
      }
   ],
   "Files" : [
      "main.ec"
   ],
   "ResourcesPath" : "",
   "Resources" : [

   ]
}
```

and  command `epj2make` then `Makefile` will be generated. 

`epj2make -o Makefile main.epj  && make`

after build with `make`, you can see `obj/release.linux/main` executable. It will execute properly without segmentation fault.

**Comment by raxod502** [comment]
Thanks for the fix! Incorporated and deployed in the above commit.
