### ISSUE TITLE
Tweak Frontend UI

### ISSUE THREAD

**Issue by rayhanadev** [radian-software/riju#63]
First off, congrats!!! Glad to see that Riju is back up and running 🚀.

Secondly, is there any specific reason why Riju has [minimal CSS](https://github.com/raxod502/riju/blob/master/frontend/styles). I'd imagine its to emphasize your fast load times but I can imagine it looking a whole lot prettier with some simple changes that barely take a second to load. It'd also make Riju look pretty in addition to fast. I do hope you consider it!

> Also random side note: your commit history is comedy gold it should be a commit convention xD

**Comment by raxod502** [comment]
Nope, there's no reason the CSS is minimal other than that styling is hard :)

I'm sure it could be greatly improved.
