### ISSUE TITLE
Add golang

### ISSUE THREAD

**Issue by itslevir** [radian-software/riju#66]
It seems that Golang is missing.

**Comment by raxod502** [comment]
are you looking for https://riju.codes/golang?

**Comment by itslevir** [comment]
Oh, my bad. I did "Control+F" and searched "Golang" instead of "Go"

**Comment by raxod502** [comment]
:)

I'd like to make it so you can do a search on the homepage, which is why I've been adding metadata to each language over time.

**Comment by itslevir** [comment]
I'd be willing to add algolia search if you'd like

**Comment by raxod502** [comment]
I don't think we need something that complicated. This just needs to be a text box that filters a list of strings.

**Comment by itslevir** [comment]
Fair enough, I should have a pull request for you tomorrow
