### ISSUE TITLE
Error While Setting Up Dev Environment 

### ISSUE THREAD

**Issue by tnb24** [radian-software/riju#76]
followed the docs step up step.

After running `make tmux` and then running `dep image:runtime` throws 
```
Error: unset environment variable: $DOCKER_REPO
```
I tried making an .env file after that and making a docker repo but it didn't work. (Throws a tags error)

Any fixes?

**Comment by raxod502** [comment]
Hey, thanks for the report! I think you're the very first person besides me to run through this documentation, so there are bound to be some bugs. I think I know what's going on and I've pushed a commit that should resolve your error. (You shouldn't need to set up any infrastructure to build Riju locally, and as such you shouldn't have to configure `$DOCKER_REPO` or `$S3_BUCKET`. I hadn't tested in that configuration yet, though, so the build system had some problems.)

Let me know if/when you run into another problem!

**Comment by tnb24** [comment]
Thanks for replying so fast. I did the process again and everything worked fine until I went to the url for the site, it shows a 502 error

**Comment by raxod502** [comment]
What's the output from `make dev`? And what URL are you using?
