### ISSUE TITLE
Create a (separated?) status page

### ISSUE THREAD

**Issue by rayhanadev** [radian-software/riju#85]
I noticed that whenever the site goes down you put up a relatively speedy notice on the issues page of this repo, however it might be beneficial to host a separated status page that shows instance health and website uptime (to name a few items). You could also add reports about downtime as well.

The best example that comes to my mind is probably [Typeform's](https://status.typeform.com/).

**Comment by raxod502** [comment]
Effective immediately, https://riju.statuspage.io/ should be updated automatically by https://uptimerobot.com/.

**Comment by raxod502** [comment]
\<sarcasm\>
&nbsp;&nbsp;&nbsp;&nbsp;Thought we should have a SEV just to make sure the status page was working: https://github.com/raxod502/riju/issues/89
\</sarcasm\>

**Comment by rayhanadev** [comment]
> Effective immediately, https://riju.statuspage.io/ should be updated automatically by https://uptimerobot.com/.

Awesome!!

> <sarcasm>
>     Thought we should have a SEV just to make sure the status page was working: #89
> </sarcasm>

LMFAO! That's actually pretty hilarious.
